### ISSUE TITLE
trademark

### ISSUE THREAD

**Issue by basisbit** [aakatev/bigbluebutton-deploy#5]
... instead of archiving the projects which violate the bigbluebutton trademark, I suggest instead just rename them and, especially, consider renaming your website name and changing the logo.
The trademark faq is quite clear on how you can use the bigbluebutton name and what is not okay.
I'd suggest you to just rename your projects to bbb-js and bbb-infra, as "bbb" is not part of the trademark registration as far as I know.

**Comment by basisbit** [comment]
![image](https://user-images.githubusercontent.com/10870269/112569373-59961500-8de4-11eb-979b-3f1ad6d35fba.png)
These especially make it look for other people like your project docs supposedly being the official docs of the bigbluebutton project, which they are not.

**Comment by basisbit** [comment]
just renaming the project and the logo and all the references and the npm package name should be enough, so others can continue using the project and contribute to it.

**Comment by aakatev** [comment]
i think i will just archive this project too. thank you
